# Generated by rust2rpm 28
%bcond check 1

%global crate tirith

Name:           rust-tirith
Version:        0.1.8
Release:        %autorelease
Summary:        Terminal security - catches homograph attacks, pipe-to-shell, ANSI injection

License:        AGPL-3.0-only
URL:            https://crates.io/crates/tirith
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Terminal security - catches homograph attacks, pipe-to-shell, ANSI
injection.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
# FIXME: no license files detected
%license LICENSE.dependencies
%doc README.md
%{_bindir}/tirith

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
